services:
    db:
        image: postgres:15-alpine
        container_name: chat-example-db
        restart: no
        ports:
            - "${POSTGRES_PORT:-5432}:5432"
        env_file:
            - ./.env
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./docker/db/init:/docker-entrypoint-initdb.d:ro
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h 127.0.0.1",
                ]
            interval: 5s
            timeout: 3s
            retries: 10

    pgadmin:
        image: dpage/pgadmin4:8
        container_name: pgadmin
        restart: no
        depends_on:
            db:
                condition: service_healthy
        ports:
            - "5050:80"
        env_file:
            - ./.env
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        volumes:
            - pgadmin_data:/var/lib/pgadmin

volumes:
    db_data:
    pgadmin_data:
